from .character_node import NODE_CLASS_MAPPINGS as CHAR_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CHAR_NODE_NAMES
from .test_node import NODE_CLASS_MAPPINGS as TEST_NODE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as TEST_NODE_NAMES

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {
    **CHAR_NODE_MAPPINGS,
    **TEST_NODE_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **CHAR_NODE_NAMES,
    **TEST_NODE_NAMES
}

# Web directory path
WEB_DIRECTORY = "./js"

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
